# wandb sweep configuration

program: scripts/identify_model.py
method: grid

metric:
  goal: minimize
  name: val_tau_loss_epoch

parameters:
  # Sweep params
  data.preprocessing.acceleration_filter_cutoff_hz:
    values: [5, 10, 20]
  data.preprocessing.measured_torque_filter_cutoff_hz:
    values: [5, 10, 20]
  dynamics_model.inertial_param_cls:
    values: [
      "${get_class:robot_payload_id.eric_id.drake_torch_dynamics.PseudoInertiaCholeskyInertialParameter}",
      "${get_class:robot_payload_id.eric_id.drake_torch_dynamics.LogCholeskyInertialParameter}",
      "${get_class:robot_payload_id.eric_id.drake_torch_dynamics.LogCholeskyLinAlgInertialParameter}",
      "${get_class:robot_payload_id.eric_id.drake_torch_dynamics.LogCholeskyComInertialParameter}",
    ]

  # Default params
  training.save_checkpoint_every_n_epochs:
    value: 100 # Only save last checkpoint
  wandb.mode:
    value: "offline"

command:
  - ${env}
  - python
  - ${program}
  - --config-name=iiwa_id.yaml
  - ${args_no_hyphens}
  - wandb.name=inertial_param_cls${dynamics_model.inertial_param_cls}_acc_cutoff${data.preprocessing.acceleration_filter_cutoff_hz}_tau_cuttoff${data.preprocessing.measured_torque_filter_cutoff_hz}
