# Sweep over data sources and data processing parameters

program: scripts/solve_inertial_param_sdp.py
method: bayes

metric:
  goal: minimize
  name: sdp_cost

parameters:
  joint_data_path:
    values: [
      "joint_data/sim/iiwa_only/bspline",
      "joint_data/sim/iiwa_only/bspline_jerkBounds",
      "joint_data/sim/iiwa_only/fourier",
    ]
  filter_positions:
    values: [true, false]
  pos_order:
    distribution: int_uniform
    min: 2
    max: 30
  pos_cutoff_freq_hz:
    distribution: uniform
    min: 1.0
    max: 60.0
  vel_order:
    distribution: int_uniform
    min: 2
    max: 30
  vel_cutoff_freq_hz:
    distribution: uniform
    min: 1.0
    max: 40.0
  acc_order:
    distribution: int_uniform
    min: 2
    max: 30
  acc_cutoff_freq_hz:
    distribution: uniform
    min: 1.0
    max: 60.0
  torque_order:
    distribution: int_uniform
    min: 2
    max: 30
  torque_cutoff_freq_hz:
    distribution: uniform
    min: 1.0
    max: 40.0

command:
  - ${env}
  - python
  - ${program}
  - --wandb_mode=online
  - --regularization_weight=0.0
  - --process_joint_data
  - --not_perform_eval
  # Providing a pre-computed base parameter mapping leads to a massive speedup
  - --base_param_mapping=logs/base_param_mapping.npy
  - ${args_no_boolean_flags}
